# Generated by Django 5.2.12 on 2026-04-03 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_fooditem_created_by_alter_nutritionlog_food_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='created_by',
        ),
    ]
