# Generated by Django 5.2.12 on 2026-04-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_fooditem_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionlog',
            name='custom_calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionlog',
            name='custom_food_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
