# Generated by Django 5.2.12 on 2026-04-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_nutritionlog_custom_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionlog',
            name='weight_in_grams',
            field=models.FloatField(blank=True, help_text='Trọng lượng món ăn (gram)', null=True),
        ),
    ]
