# Generated by Django 5.2.12 on 2026-04-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_nutritionlog_weight_in_grams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='category',
        ),
        migrations.AddField(
            model_name='exercise',
            name='categories',
            field=models.ManyToManyField(related_name='exercises', to='mainapp.exercisecategory'),
        ),
    ]
