# Generated by Django 5.2.12 on 2026-04-04 01:26

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_exercise_category_exercise_categories'),
    ]

    operations = [
        UnaccentExtension(),
    ]
