# Generated by Django 5.2.12 on 2026-04-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20260404_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutlog',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='duration_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
