# Generated by Django 5.2.12 on 2026-03-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Đang chờ xử lý'), ('Active', 'Đang thực hiện'), ('Completed', 'Đã hoàn thành'), ('Expired', 'Hết hạn')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(help_text='Tuần thứ mấy trong lộ trình')),
                ('target_calories', models.FloatField(help_text='Lượng Calo mục tiêu mỗi ngày trong tuần này')),
                ('suggested_macros', models.CharField(help_text='Tỷ lệ P:C:F (ví dụ 30:40:30)', max_length=200)),
                ('note', models.TextField(blank=True, help_text='Lời khuyên cụ thể cho giai đoạn này', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ví dụ: Giảm cân bền vững 4 tuần', max_length=200)),
                ('description', models.TextField(help_text='Mô tả tổng quát về hướng tiếp cận của lộ trình')),
                ('estimated_result', models.CharField(help_text='Kết quả dự kiến (VD: Giảm 2kg mỡ)', max_length=200)),
                ('is_selected', models.BooleanField(default=False, help_text='Đánh dấu nếu người dùng chọn phương án này')),
            ],
        ),
    ]
