# Generated by Django 5.2.12 on 2026-03-18 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='airecommendationplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planoption',
            name='recommendation_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='ai_engine.airecommendationplan'),
        ),
        migrations.AddField(
            model_name='plandetail',
            name='plan_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='ai_engine.planoption'),
        ),
    ]
