# Generated by Django 5.2.12 on 2026-03-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plandetail',
            name='week_number',
        ),
        migrations.AddField(
            model_name='plandetail',
            name='day_number',
            field=models.IntegerField(default=0, help_text='Ngày thứ mấy trong lộ trình'),
            preserve_default=False,
        ),
    ]
