# Generated by Django 5.2.12 on 2026-04-05 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_remove_plandetail_week_number_plandetail_day_number'),
        ('mainapp', '0008_remove_workoutlog_duration_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plandetail',
            name='suggested_macros',
        ),
        migrations.CreateModel(
            name='PlanDayExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_sets', models.IntegerField(default=3)),
                ('suggested_reps', models.IntegerField(default=12)),
                ('duration_seconds', models.IntegerField(help_text='Thời gian dự kiến tập bài này (giây)')),
                ('estimated_calories_burned', models.FloatField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.exercise')),
                ('plan_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='ai_engine.plandetail')),
            ],
        ),
    ]
