# Generated by Django 5.2.12 on 2026-04-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0004_remove_plandetail_suggested_macros_plandayexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandetail',
            name='is_finished',
            field=models.BooleanField(default=False, help_text='Đánh dấu ngày tập này đã hoàn thành'),
        ),
    ]
