# Generated by Django 5.2.12 on 2026-04-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0005_plandetail_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
