# Generated by Django 5.2.12 on 2026-04-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0006_plandetail_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandayexercise',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
